### ISSUE TITLE
Support more region types

### ISSUE THREAD

**Issue by Palmidence** [Warzone/TGM#101]
We have cylindrical and cuboid, however we do not have many regions.

# Sphere:

```
center: 4, 32, -66
radius: 12
```

Keeping regions as cylinders is not a shape that works for every map: where there's maps like Avalanche Mini that have spawns that are burrowed into a mountain, a sphere would work best so it doesn't interfere with other regions, especially if the objective is relative to the spawn or above it. Spheres are much more practical since they are more precise for exactly where you want a region to be.

# Hemisphere:

```
center: 4, 32, -66
radius: 8
position: below | above
```

There may be cases where there's one part of a sphere you wish to protect but the other part you want to allow for building and such. One example may be a map with an oddly shaped spawn where special goods are below the spawn, but you don't want to prevent them from interacting with the area. The math for this should be easy if you get the sphere region coded.

# Infinite

```

infinite: true

```

Using a boolean, we should be able to use an `infinite` region that extends beyond the whole map and acts as a supported `oo,oo,oo`. Using the infinite region, we could do things like prevent building or other things later on when JSON gets more advanced.

**Comment by CrazyisCreeps** [comment]
Looks like all but hemisphere have been added, however I'd also like to see an additional couple;

- An easy way to set a build height on maps

- A void filter [similar to PGM's](http://docs.oc.tc/modules/filters#voidFilter), allowing for easy control over where players can and can't bridge in a map, thus limiting them to the intended areas

- Inverse/negative functionality for regions, where the inverse/negative region ends up being everywhere the other region isn't

**Comment by jorgeberrex** [comment]
Fully implemented.
