### ISSUE TITLE
Sudden Death

### ISSUE THREAD

**Issue by ghost** [Warzone/TGM#138]
_**Sudden Death**_

> Make it so when the match gets too long, like 20 minutes, it turns to sudden death and maybe all of the monuments go to 10% for DTW and for CTW you only have to capture 1 for the game to end. Or maybe it goes to 50% at 10 minutes and 10% at 20 minutes. But if one monument already is below 50% it just stays as it is. Or maybe if the game gets to 25-30 minutes the game just ends. I don't think any game has ever gotten to 30 minutes though.

**Why Should This Be Added -** This should be added because sometimes matches get too long and everyone spams "/end the game please" and it would be a cool thing to add to prevent long matches. 

**Additional Comments** - I think this is a really good idea because it could help prevent long matches.

**Comment by Virtualizes** [comment]
This would be good for a map like Terrace because that map goes up to over 25 minutes sometimes.

**Comment by Whnd** [comment]
yes pls

**Comment by DeternoMC** [comment]
Instead of sudden death, make a match end. I'm not bothered looking for people who's hiding somewhere in the map whilst sudden death is on. With the match end, whoever is in the lead wins, if not it's a draw

**Comment by Arkrus** [comment]
Then just have a glowing effect. I know 1.8 players don't get the effect but they shouldn't be playing in 1.8 anyway.

**Comment by Hxnr** [comment]
I believe sudden death could work for DTW but not for CTW.

**Comment by AtditC** [comment]
This should be closed because long matches happen rather rarely and when they happen, it's a good thing, because it adds variety.
