### ISSUE TITLE
Add support for multiple spawn points

### ISSUE THREAD

**Issue by tjhubz** [Warzone/TGM#160]
Spawnpoints should be more customizable then they are currently. This would include random (spread players-like) spawn points and multiple spawn points.

**Comment by Synconix** [comment]
Maybe their could be a gamemode for this so like 2 people don't spawn right next to eachother and instantly die

**Comment by DeternoMC** [comment]
@Synconix "instantly die" elaborate please

**Comment by Synconix** [comment]
Maybe this could be a separate gamemode or map so map makers don't have to edit their current maps
