### ISSUE TITLE
Chest filling up with wool

### ISSUE THREAD

**Issue by BennyDoesStuff** [Warzone/TGM#255]
When a player picks up a piece of wool and puts it in an empty the chest, the chest becomes a wool chest and constantly fills up with wool.

**Comment by TheRealPear** [comment]
Does this work outside of the woolhouse or inside?

**Comment by JapaneseSquid** [comment]
I know for a fact that it works inside the wool room but I don’t know about outside of it

**Comment by JapaneseSquid** [comment]
In fact, I went into creative once to fix a griefed wool room that had a broken chest just by placing chests and one piece of wool in it
