### ISSUE TITLE
Include a default map with the plugin

### ISSUE THREAD

**Issue by BennyDoesStuff** [Warzone/TGM#444]
If there are no maps in the maps folder, the plugin should automatically load a default map so the server starts up and so the plugin doesn't actually fail to load. That way, people can easily use the /loadmaps to then include any upload any other maps they want to add without having to restart the server.

**Comment by Owehttamy** [comment]
Would this be an actual functional map, or would it just be a void world with a platform to give instructions? (Or something along those lines)

**Comment by AtditC** [comment]
> Would this be an actual functional map, or would it just be a void world with a platform to give instructions? (Or something along those lines)

Don't know what Benny thinks but imo it should be a very simple, playable DTW map. Something like Core Test TE on Avicus.

**Comment by BennyDoesTheStuff** [comment]
What @AtditC said. It’s just something so the plugin loads and starts up if for some reason it can’t find any maps to load.
