### ISSUE TITLE
Nicks don't work on #server-chat

### ISSUE THREAD

**Issue by AtditC** [Warzone/TGM#536]
**Describe the bug**
When nicked in-game, messages on #server-chat still have the original username. I know this has nothing to do with TGM but where else should it be reported if not here? TGM could perhaps cancel nicked player's messages so it won't get to DiscordSRV? I'm not sure if anything can be done about that, but otherwise once someone figures out this bug, they could always check in #server-chat to see the nicked player's original name which defeats the purpose of nicking as they would be exposed.

**To Reproduce**
Steps to reproduce the bug:
1. /nick set <name>
2. Type something in chat
3. #server-chat uses the original name

**Comment by AtditC** [comment]
I didn't mean to add the bug label

**Comment by Draem** [comment]
This doesn't happen anymore, although DiscordSRV changes your nick on Discord to your in game nickname

**Comment by BennyDoesTheStuff** [comment]
Nicknames do seem to be showing on the server-chat now. It no longer shows your real IGN. Closing.
