### ISSUE TITLE
Add Suffixes (tags)

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [Warzone/TGM#555]
**Describe the feature you'd like**
The ability to give players suffixes (tags) and allow them to enable which ones to use in a /tags GUI.

**Usefulness of the feature**
Could be added as a purchasable cosmetic to help support the server.

**Additional context**
This feature is currently in the [Manager](https://github.com/WarzoneMC/Manager) plugin, however, the manager plugin is outdated and it makes no sense to have tags in a separate plugin if we have ranks and everything else in the TGM plugin.

**Comment by MrScopes** [comment]
yes please
