### ISSUE TITLE
Capture the Flag

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [Warzone/TGM#567]
**Describe the feature you'd like**
This should be another gamemode quite similar to CTW, but instead of needing to capture wool, you'll need to capture flags.

It should be called "Capture The Flag" or "CTF" for short.

**More Information**

- In the JSON, the map maker will define where the player needs to run to so the flag is captured and where the player needs to run to in order to pick up the flag.
- The number of times the team needs to capture the flag/flags should be definable in the JSON as well.
- This gamemode should be able to handle as many teams as defined in the JSON (unlimited).
- Once a player picks up a flag, they should receive a banner on their hat and they should lose their inventory so that they are weakened. We could also give them certain effects such as slowness or something (could be definable in the JSON as well).
- The team that captures the # of required flag captures first before the other team/teams win.

**Comment by ThatOneTqnk** [comment]
How should the scoreboard for this look like if there are a large amount of teams?

**Comment by residesJack** [comment]
something similar to this could work 
![image](https://user-images.githubusercontent.com/55336990/68177921-ff719580-ffdd-11e9-83c5-6e1c7953829f.png)

**Comment by ThatOneTqnk** [comment]
Hmm, there needs to be some clarification here, the original feature request says that the gamemode is similar to CTW, which led me to believe that each flag is only captured once. Should it be "points-based", similar to CTW, or have options for both?

**Comment by Owehttamy** [comment]
Have options for both. Might as well spend time implementing more json flexibility.

**Comment by residesJack** [comment]
on stratus you have to run to the other side and walk into the flag, then you deliver it back to where your own flag is located. you usually do that three times depending on what the author wants. that seems like the best idea. but yeah, it would be good to have options for both.

**Comment by ThatOneTqnk** [comment]
alrite ye, both seems good
