### ISSUE TITLE
Add empty line to scoreboard

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [Warzone/TGM#584]
**Describe the feature you'd like**
Add an empty line below the Objectives  on the scoreboard

**Usefulness of the feature**
Makes the scoreboard look better

**Additional context**
How the scoreboard looks currently:
![image](https://i.imgur.com/bghdSQ1.png)

**Comment by Owehttamy** [comment]
Also could we make it possible to center the ip on the scoreboard?
