### ISSUE TITLE
Resolve kill credit issue 

### ISSUE THREAD

**Issue by residesJack** [Warzone/TGM#588]
**Describe the bug**
Here's an example. P1 initiates a fight with P2, P1 gets the last hit on P2, however P3 was assisting P1 and got the second-last hit on P2. 

The kill credit would be incorrectly given to P3. The player who should have gotten the credit for the kill was P1.

**Client version**
1.8.9 

**To Reproduce**
Steps to reproduce the bug:
1. Kill a player 
2. Someone else gets the second last hit on the player.
3. Read chat

**Expected behavior**
Kill credit is given to the player who hit the person last.

**Server Software (Spigot/PaperSpigot):**
PaperSpigot

**Comment by jorgeberrex** [comment]
Fixed in 324243c2a7c95817812fcd5d19bb6cf9ad6f3c52
