### ISSUE TITLE
Bow knockback inconsistency

### ISSUE THREAD

**Issue by Owehttamy** [Warzone/TGM#601]
**Describe the bug**
Knockback is *pretty* off from 1.8 knockback.

**To Reproduce**
1. Shoot an enemy.

**Expected behavior**
Knockback behaves like (or as similar to) version 1.8's knockback.

**Additional context**
Please tweak

**Comment by benrobson** [comment]
Did the PR fix this issue?
Can this be closed?

**Comment by BennyDoesStuff** [comment]
With all the recent commits I’m going to close this for now. If this is still an issue we can always reopen, but I don’t think this is.
