### ISSUE TITLE
Make hotbars customizable to each player

### ISSUE THREAD

**Issue by Owehttamy** [Warzone/TGM#602]
**Describe the feature you'd like**
Set up a system where players can set which items are put in which slots inside of their inventories. Then that would be used on every map.

Example: Swords in slot 1, Bows in slot 2, blocks in slot 3, tools in slot 4, etc.
Then if the map doesn't have bows, then everything in the slots after it gets moved left on the sidebar.

**Usefulness of the feature**
People won't have to sort their inventories on some maps during every respawn.

**Additional context**
Someone like Hypixel's Bedwars item sorting, or Hypixel's duels.

**Comment by BennyDoesTheStuff** [comment]
The issue with this is each map has a different hotbar and layout. This is different from the example you're talking about since all bedwars maps have the same hotbar and all duels maps have the same hotbar per gamemode.

How do you think we should then save the customized hotbars? What happens if a map is removed, what happens to their saved hotbar?

**Comment by Owehttamy** [comment]
The saved hotbars aren't customized by map, but are the same throughout every map. (or maybe per gamemode idk) The hotbars are customized by how the player prefers their hotbar to typically be setup for every map; not by what map they're playing on.

Generally the items could be saved in categories, for example all of the swords are one category, etc.

**Comment by MrScopes** [comment]
since there is a rotation, what if it saved your current hotbar layout at the end of the game to use for the next time you play that map

**Comment by BennyDoesTheStuff** [comment]
@MrScopes then we would need to save it somewhere. I think the best solution is this:

Right now there's around 20 seconds before a game starts. Before the game starts, you should have the ability to choose your hotbar/loadout for that match. You should also be able to choose your hotbar while you're respawning as well as while as a spectator. This wouldn't cause any issues with needing to store the hotbars, while still allowing players to organize the hotbar and inventory as they would like to organize it.

**Comment by BennyDoesStuff** [comment]
#693
