### ISSUE TITLE
Add /github command 

### ISSUE THREAD

**Issue by residesJack** [Warzone/TGM#606]
**Describe the feature you'd like**
A command that links you to Warzone's github.

**Usefulness of the feature**
If players wanted to contribute to the server and didn't know how, they can type /github in-game instead of joining the Discord server and finding out that way.

**Comment by BennyDoesTheStuff** [comment]
I'm not sure if this is something we should implement into TGM. The link to the plugin can be seen already when someone types /version TGM so I'm not sure how helpful a /github command would be.

**Comment by MrScopes** [comment]
> I'm not sure if this is something we should implement into TGM. The link to the plugin can be seen already when someone types /version TGM so I'm not sure how helpful a /github command would be.

I mean, people ought to know where TGM comes from. Maybe the github link could be in the config?

**Comment by BennyDoesTheStuff** [comment]
I mean if you’re using TGM on a server, you already know what the GitHub is. And if you’re interested in contributing, we already have broadcasts setup that advertise our GitHub so adding a command like this is unnecessary
