### ISSUE TITLE
Allow players to instantly break blocks once the game ends

### ISSUE THREAD

**Issue by Owehttamy** [Warzone/TGM#607]
**Describe the feature you'd like**
Once a match ends, players who participated in the game can instantly break all of the blocks on the map.

**Usefulness of the feature**
1000° fist vs. Warzone map
(Mainly for entertainment reasons, also to be able to let players get out of places they block themselves into)

**Additional context**
Saw it on another server and it was very enjoyable so please add ty

**Comment by BennyDoesTheStuff** [comment]
This feature would be a cool feature if it's something implemented as a possible donator perk. I don't think it would look that professional if we suddenly have the whole server starting to fly around and break the map. I would personally be fine with it if it was something that could be enabled/disabled in the config, as well as only usable with a permission node. By default though, it should be a feature that could be disabled in the config.

**Comment by Draem** [comment]
DM has it and they're very professional and serious :+1:

**Comment by MrScopes** [comment]
benny i could make it a perm node in the config
