### ISSUE TITLE
Add ranks to Tablist

### ISSUE THREAD

**Issue by Owehttamy** [Warzone/TGM#608]
**Describe the feature you'd like**
Title is self-explanatory

**Usefulness of the feature**
A little bit more incentive to buy a rank (whenever the store comes back)

**Comment by BennyDoesTheStuff** [comment]
The tab is already filled up with levels, and adding ranks would only make tab look even more messy. This would also make it harder for staff members to moderate

**Comment by Draem** [comment]
Nick command bruh

**Comment by BennyDoesTheStuff** [comment]
True, but adding ranks to tab would just make it way messy and they don’t actually show much useful info the player might need while playing the match

**Comment by Draem** [comment]
Get this guy out of here.
