### ISSUE TITLE
/nicks lists offline nicked players

### ISSUE THREAD

**Issue by AtditC** [Warzone/TGM#613]
**Describe the bug**
/nicks lists nicked players which are offline when the command is executed. It'd be better if it A) didn't list them at all when they're offline or B) add an " (offline)" to the line

**Client version**
1.8.9, but it will appear at any version

**To Reproduce**
1. Have an account be nicked
2. Log out with the nicked account
3. Execute /nicks with another account
4. See the nicked account's name

**Expected behavior**
Only show online nicked players

**Screenshots**
![image](https://user-images.githubusercontent.com/7355350/68550827-dcdce380-0406-11ea-9b9a-0007b8896261.png)

**Server Software (Spigot/PaperSpigot):**
PaperSpigot on Warzone

**Additional context**
Actually it's something between a bug and a feature request but it's hard to decide where to put it so I just put it here

**Comment by MrScopes** [comment]
not really a bug

**Comment by BennyDoesTheStuff** [comment]
I think it's fine to show offline nicked players. Nicked players get reset everything the server restarts, so it's not like the players aren't nicked. They are still nicked when they join back, so it would be nice to see who is still nicked.
