### ISSUE TITLE
No maps in rotation

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [Warzone/TGM#617]
**Describe the bug**
If there are no maps in the rotation, the plugin doesn't load

**To Reproduce**
Steps to reproduce the bug:
1. Create a rotation but don't include any maps or don't create a rotation.
2. Start the server

**Expected behavior**
It should just send an error and continue to load the plugin with the first map in the maps repo/folder.

**Server Software (Spigot/PaperSpigot):**
PaperSpigot 1.14.4

**Comment by Draem** [comment]
Can confirm
