### ISSUE TITLE
Spectators hear sounds of pain

### ISSUE THREAD

**Issue by Owehttamy** [Warzone/TGM#620]
**Describe the bug**
Occasionally when a player dies in a match, their last damage sound is played to the spectator spawn, rather than where they actually last got hurt, meaning that the poor spectators are hearing people get ouchied.

**Client version**
All

**To Reproduce**
Steps to reproduce the bug:
1. Don't join a team
2. Have other people start playing (the more the better)
3. Wait at spectator spawn
4. Hear the sounds of the damned
5. Profit

**Expected behavior**
Spectators don't become paranoid

**Comment by Draem** [comment]
not reproducible on 1.8.9 lunar

**Comment by Owehttamy** [comment]
(resolved)
