### ISSUE TITLE
Cycling between maps semi freezes the Server.

### ISSUE THREAD

**Issue by benrobson** [Warzone/TGM#637]
**Describe the bug**
In between the match ending and cycling to load the next map, the server freezes for about 10-15 seconds.

**Client version**
Minecraft 1.15.2

**To Reproduce**
Just simply start and stop a match and cycle.

**Expected behaviour**
The Server to cycle and the next map to instantly load.

**Screenshots**
N/A

**Server Software (Spigot/PaperSpigot):**
Minecraft server version 1.15.2
Paper version git-Paper-79 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Additional context**
I am running this Server I didn't find this in Warzone.
The Server itself is running in the latest 1.15.2 in a BungeeCord instance. 
This instance is running with 10GB dedicated to it.

**Comment by BennyDoesTheStuff** [comment]
I would first make sure the maps you are using are up-to-date (1.15.2). But otherwise, I'm not too sure what might be causing that. On the production server (Warzone), maps do take 3 - 4 seconds to load, but nothing as long as you are describing.

![Image](https://i.imgur.com/sc5enhz.png)
