### ISSUE TITLE
Dropping items make them disappear

### ISSUE THREAD

**Issue by nichxlxs** [Warzone/TGM#642]
**Describe the bug**
When you drop an item, for example, sword, you've lost it. It doesn't drop on the ground it just disappears.

**Client version**
Tested on 1.15.2, though it probably happens on all versions

**To Reproduce**
Drop an item in game. Not sure which map it occurs on, but I know it's happened a few times.

**Expected behavior**
Either cancel the drop and keep it in the inventory, or make it go on the floor.

**Screenshots**
N/A

**Server Software (Spigot/PaperSpigot):**
N/A

**Additional context**
N/A

**Comment by BennyDoesTheStuff** [comment]
I'm not sure if this is a bug, in the JSON we have all items defined in the item remove so that it's removed when the player dies.

**Comment by jorgeberrex** [comment]
Not a bug. This is intended behavior by the ItemRemoveModule.
