### ISSUE TITLE
Teleported to random location when game started

### ISSUE THREAD

**Issue by nichxlxs** [Warzone/TGM#643]
**Describe the bug**
Game started and was teleported to spawn then to a random location.

**Client version**
1.15.2

**To Reproduce**
Unknown.

**Expected behavior**
Spawn at the correct spawnpoint

**Screenshots**
https://www.youtube.com/watch?v=rNHjSFtGzLs - Video of it occuring

**Server Software (Spigot/PaperSpigot):**
N/A

**Additional context**
N/A

**Comment by AtditC** [comment]
It could have to do with the lag. The boss bar froze on "Match starting in 1 second" for a few seconds, indicating a lag spike. When the lag was over, you first got teleported to spawn, and then back to the last position where you were standing on a block (Match starting in 4 seconds, 0:01) before the lag occurred.

**Comment by JapaneseSquid** [comment]
The real issue here is the crouch spam in the bridging

**Comment by BennyDoesStuff** [comment]
Closing this issue as I haven't seen this happen before and we don't know how to reproduce. If this does pop up again in the future, we can always reopen this.
