### ISSUE TITLE
Allow players to view their statistics starting from 2 weeks ago, 1 month ago, etc 

### ISSUE THREAD

**Issue by residesJack** [Warzone/TGM#649]
**Describe the feature you'd like**
This feature allows players to view their statistics starting from 2 weeks ago, 1 month ago, etc 
e.g ; /stats Residents 2w, 1mo, 3mo, 1yr, 

**Usefulness of the feature**
This addition grants players with insight on how they have improved and will be great for people who are interested in seeing their stats from a certain point.

**Comment by BennyDoesTheStuff** [comment]
Warzone/api#26
