### ISSUE TITLE
Allow plugin to fully start on first boot

### ISSUE THREAD

**Issue by MatrixTunnel** [Warzone/TGM#656]
- Auto create maps folder if not present
- Auto create default rotation (maybe download a template file from a repository or bundle it in the plugin resources with a simple default map)
- Prevent plugin from starting if configuration is invalid
- Better setup documentation
- Fix errors

**Comment by BennyDoesTheStuff** [comment]
If no rotation is present, the plugin auto adds all the maps it can find to the rotation. We would probably just need the ability to load the plugin without any maps loaded or added in, that way the owner could then add some and /loadmaps.

**Comment by BennyDoesTheStuff** [comment]
Maybe we could potentially include a default map in the plugin itself so if the plugin can’t find the maps folder, it could at least cycle to something until the server owner can fix and add some maps.
