### ISSUE TITLE
rot thing

### ISSUE THREAD

**Issue by PundaChen** [Warzone/TGM#687]
**Describe the feature you'd like**
Make it so the rot doesnt start at the beginning when it switches rots

**Usefulness of the feature**
The first few maps are really repetitive and annoying to play now

**Comment by benrobson** [comment]
I suggested the idea of having to be able to shuffle maps in rotations when a rotation loads, which stops the first few maps being "really repetitive and annoying to play".
Tank worked on this yesterday: https://github.com/chatasma/Warzone/tree/shufflerot and hopefully will be tested and merged.

Whenever I have time I will work on testing it.

**Comment by benrobson** [comment]
Once @BennyDoesStuff updates to latest commit, this can be closed.
