### ISSUE TITLE
If TGM has no /Maps directory or rotation file, crash the Server with an error message.

### ISSUE THREAD

**Issue by benrobson** [Warzone/TGM#690]
**Describe the feature you'd like**
Basically as indicated as the title, if there are no maps in the specified maps directory or if there is no rotations.json, crash the server and flag the issue to the Administrator in the Console.

**Usefulness of the feature**
This would help Administrators in troubleshooting rather than just throwing a rhythmic error.

**Comment by BennyDoesStuff** [comment]
In terms of the rotation file, the server automatically adds all the maps on the server to the rotation if it cannot find a rotation. Though regarding the server not finding any maps, other related issues already exist such as #444 and #656 so I'm going to close this.
