### ISSUE TITLE
Stat Tracking Command

### ISSUE THREAD

**Issue by AtditC** [Warzone/TGM#698]
**Describe the feature you'd like**
A command, such as _/stats tracking <on|off_> or _/stattracking <on|off>_ or something similar, which can turn stat tracking on or off on any map. Right now, disabling stats can only be done via the config or map json. It'd be nice to disable stat tracking perhaps for future tournaments or certain events. This could also be used to enable stat tracking on maps where stats have been turned off via the json.

**Usefulness of the feature**
- In a tournament, where stats can easily get worse due to the higher skill level compared to the average public game, disabling stat tracking would be very helpful. This could potentially mean, that more players will attend tournaments because they don't have to fear ruining their stats (this won't matter as much for players with a lot of kills/wins, however other newer players might care).
- When we let one or two players fight against all other players in public matches for fun, disabling stats wouldn't ruin the smaller team's stats.
- A possible scenario, where punishments commands won't work anymore due to a bug or a failing API, we could disable stat tracking temporarily so hackers can't ruin the stats of their victims.

**Additional context**
No.

**Comment by BennyDoesStuff** [comment]
This functionality already exists in TGM, you can use the **/config stats (off/on)** command to disable/enable stat tracking whenever you want.
