### ISSUE TITLE
Chat messages during cycling are broken

### ISSUE THREAD

**Issue by AtditC** [Warzone/TGM#699]
**Describe the bug**
Whenever the map cycles and you send a message, the message appears as an empty new line.

**Client version**
1.8.9, will happen on any version though, I'm pretty sure

**To Reproduce**
Steps to reproduce the bug:
1. Wait until a map is over and the cycle countdown is finished
2. Send a message

**Expected behavior**
The message will appear as an new line

**Screenshots**
![image](https://user-images.githubusercontent.com/7355350/105227830-0e505380-5b62-11eb-82bb-63200a3f1dfa.png)
The messages as they appear ingame when cycling between maps

![image](https://user-images.githubusercontent.com/7355350/105227913-2b852200-5b62-11eb-807c-442712338b0c.png)
The messages which should've appeared between the two players joining, which can be found on Discord when using DiscordSRV

**Server Software (Spigot/PaperSpigot):**
PaperSpigot 36d7de3 (MC 1.16.4)

**Additional context**
No.

**Comment by BennyDoesStuff** [comment]
This is because all the modules (including the chat module) is being unloaded and loaded again while the map is being cycled. Something like #493 would fix this
