### ISSUE TITLE
Tell CTF flag holder what to do

### ISSUE THREAD

**Issue by AtditC** [Warzone/TGM#709]
**Describe the feature you'd like**
Whenever someone picks a flag up in CTF, he should get a bold message which tells him to bring it back to his own flag base.

**Usefulness of the feature**
CTF is a "new" gamemode on Warzone, not a lot of players know what they have to do once they pick up the flag.

**Additional context**
I've seen players bring it back to spawn before finding out they have to bring it to the flag base.

**Comment by master00ofdsiware** [comment]
Implemented in #719
This issue can be closed.
