### ISSUE TITLE
Balancing Teams Based On Level

### ISSUE THREAD

**Issue by ballxishot** [Warzone/TGM#742]
**Describe the feature you'd like**
When players that have not got a rank join a team they are placed on different teams based on levels.

**Usefulness of the feature**
This feature would be useful because then it would make the games more balanced and funner for the community!

**Additional context**
I heard it may be implemented but wanted to make a commit so it will definitely be implemented!!

**Comment by residal** [comment]
When a player has a rank, that doesn't necessarily mean that they're good. There are better ways to resolve the skill gap than this.

**Comment by BennyDoesStuff** [comment]
Duplicate issue
