### ISSUE TITLE
Joining spectators pre-match drops the spectator kit

### ISSUE THREAD

**Issue by AtditC** [Warzone/TGM#743]
**Describe the bug**
If you leave a team you've joined before the match has started, you will drop your spectator kit.

**Client version**
1.16.5

**To Reproduce**
1. Join any team before the match has started
2. Join spectators
3. The spectator kit is dropped

**Expected behavior**
The spectator kit should not be dropped under any circumstances.

**Screenshots**
https://www.youtube.com/watch?v=cIP3f0_zpKk

**Server Software (Spigot/PaperSpigot):**
Paper 470 (1.16.5)

**Additional context**
No.

**Comment by jorgeberrex** [comment]
Fixed by https://github.com/Warzone/TGM/commit/d3d305bb6b43a1b1e48af513a0401c6e0024d538
