### ISSUE TITLE
ItemCanPlaceOnParser should allow selecting all blocks

### ISSUE THREAD

**Issue by TBG1000** [Warzone/TGM#768]
**Describe the feature you'd like**
Similar to the ItemRemoveModule, the ItemCanPlaceOnParser should allow the mapmaker to select all blocks to place items on.

**Usefulness of the feature**
Useful for maps where adventure mode is assigned to teams.

**Additional context**
Issue that came up with a recent map.
Tried the following with no success:
```
"canPlaceOn": *
"canPlaceOn": "*"
"canPlaceOn": [*]
"canPlaceOn": ["*"]
```

**Comment by jorgeberrex** [comment]
I'm afraid this is not feasible as the `canPlaceOn` tag is stored within the item NBT and it is not handled by TGM. This basically means that, to allow all materials, we would need to store all of Minecraft's available materials (1k+) inside the item NBT which can be potentially dangerous from a technical point of view.
