### ISSUE TITLE
Implement new/old colours for levels 220-240 & 240-260

### ISSUE THREAD

**Issue by residal** [Warzone/TGM#785]
Levels 220-240 & 240-260 should be given different colours, since every level over 200 has the same colour.

They could either be an unused colour or a colour from a lower level.

**Comment by BennyDoesStuff** [comment]
https://github.com/Warzone/TGM/blob/master/TGM/src/main/resources/config.yml

Colors are all customizable through TGM's configuration which can be changed on a per-server basis. The ones provided in TGM are simply just the default values.
