### ISSUE TITLE
items/effect at specific times

### ISSUE THREAD

**Issue by tjhubz** [Warzone/TGM#79]
When there are 30 seconds left in a match, all humans should get glowing.

**Comment by Hxnr** [comment]
Should be customizable per-map in the JSON.

**Comment by BennyDoesTheStuff** [comment]
Instead of specifically added a feature to give glowing, I feel like we should instead add a way to give certain items/effects to players when there's x minutes left. It should be the same as one we have for killstreaks, but instead of getting whatever on x kills, you would get it at x time left.

**Comment by BennyDoesStuff** [comment]
Looks like this already exists in TGM. I'm not sure when it was implemented, but someone must've forgotten to close this issue.

Reference: [https://docs.warz.one/#/mechanics/time](https://docs.warz.one/#/mechanics/time)
